### Scalars

In [3]:
import torch

In [4]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)
tab = [x + y, x * y, x / y, x**y, x - y, 2*x - 4*y]
tab = map(str, map(float, tab))
print(" | ".join(tab))

5.0 | 6.0 | 1.5 | 9.0 | 1.0 | -2.0


### Vectors

In [5]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [6]:
x[2], x[-1], x[0], x[:2], x[1:], x[::2]

(tensor(2),
 tensor(2),
 tensor(0),
 tensor([0, 1]),
 tensor([1, 2]),
 tensor([0, 2]))

In [7]:
len(x), len(x[:1]), len(x[::2]), len(x[5::])

(3, 1, 2, 0)

In [8]:
x.shape, x[:2].shape

(torch.Size([3]), torch.Size([2]))

### Matrices

In [9]:
A = torch.arange(6).reshape(3, 2)
A, A.shape

(tensor([[0, 1],
         [2, 3],
         [4, 5]]),
 torch.Size([3, 2]))

In [10]:
A[0], A[1], A[2], A[1:3]

(tensor([0, 1]),
 tensor([2, 3]),
 tensor([4, 5]),
 tensor([[2, 3],
         [4, 5]]))

In [11]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [12]:
A = torch.tensor([[1, 2, 3], [2, 2, 4], [3, 4, 5]])
print(A, '\n')
print(A.T, '\n')
A == A.T

tensor([[1, 2, 3],
        [2, 2, 4],
        [3, 4, 5]]) 

tensor([[1, 2, 3],
        [2, 2, 4],
        [3, 4, 5]]) 



tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

### Tensors

In [13]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [14]:
X.shape

torch.Size([2, 3, 4])

In [15]:
X[1], x[1:]

(tensor([[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]),
 tensor([1, 2]))

### Basic Properties of Tensor Arithmetic

In [16]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()  # Assign a copy of A to B by allocating new memory
A, A + B, A*3, A*B, A**2, A*B == A**2

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]),
 tensor([[ 0.,  3.,  6.],
         [ 9., 12., 15.]]),
 tensor([[ 0.,  1.,  4.],
         [ 9., 16., 25.]]),
 tensor([[ 0.,  1.,  4.],
         [ 9., 16., 25.]]),
 tensor([[True, True, True],
         [True, True, True]]))

In [17]:
A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [18]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
print("X:", X, '\n')
a + X, (a * X).shape

X: tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]) 



(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

### Reduction

In [19]:
x = torch.arange(3, dtype=torch.float32)
print("x:", x, '\n')
x, x.sum(), x.mean(), x.median()

x: tensor([0., 1., 2.]) 



(tensor([0., 1., 2.]), tensor(3.), tensor(1.), tensor(1.))

In [20]:
print("A:", A, '\n')
A.shape, A.sum()

A: tensor([[0., 1., 2.],
        [3., 4., 5.]]) 



(torch.Size([2, 3]), tensor(15.))

In [21]:
A.sum(axis=0), A.sum(axis=1), A.sum(axis=0).shape, A.sum(axis=1).shape

(tensor([3., 5., 7.]), tensor([ 3., 12.]), torch.Size([3]), torch.Size([2]))

In [22]:
A.sum(axis=[0, 1]), A.sum(), A.sum(axis=[0, 1]) == A.sum()

(tensor(15.), tensor(15.), tensor(True))

In [23]:
A.mean(), A.sum() / A.numel()

(tensor(2.5000), tensor(2.5000))

In [24]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))

In [25]:
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

### Non-Reduction Sum

In [26]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A, sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [27]:
A / sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [28]:
A, sum_A

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 3.],
         [12.]]))

In [29]:
A.cumsum(axis=0)

tensor([[0., 1., 2.],
        [3., 5., 7.]])

### Dot Products

In [30]:
y = torch.ones(3, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [36]:
y = torch.ones(3)
torch.dot(x, y), y.dtype

(tensor(3.), torch.float32)

In [37]:
torch.sum(x * y)

tensor(3.)

### Matrix–Vector Products

In [38]:
A, x

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([0., 1., 2.]))

In [42]:
A.shape, x.shape, torch.mv(A, x), A@x

(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

In [44]:
(A@x).shape

torch.Size([2])

### Matrix–Matrix Multiplication

In [47]:
B = torch.ones(3, 4)
A, B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [46]:
torch.mm(A, B), A@B

(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

### Norms

#### Euclidean norm (L2)

In [48]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

#### Manhattan distance (L1)

In [49]:
torch.abs(u).sum()

tensor(7.)

#### Frobenius norm

In [51]:
p = torch.ones((4, 9))
p

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [52]:
torch.norm(torch.ones((4, 9)))

tensor(6.)