## Parameter Initialization

In [1]:
import torch
from torch import nn

In [2]:
net = nn.Sequential(nn.LazyLinear(8), nn.ReLU(), nn.LazyLinear(1))
X = torch.rand(size=(2, 4))
net(X).shape

C:\Users\hub30\anaconda3\envs\d2l\lib\site-packages\torch\nn\modules\lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


torch.Size([2, 1])

### Built-in Initialization

In [5]:
def init_normal(module):
    if type(module) == nn.Linear:
        nn.init.normal_(module.weight, mean=0, std=0.01)
        nn.init.zeros_(module.bias)

net.apply(init_normal)
net[0].weight.data[0], net[0].bias.data[0], net[2].weight.data[0], net[2].bias.data[0]

(tensor([-0.0014,  0.0165, -0.0038, -0.0104]),
 tensor(0.),
 tensor([-0.0017, -0.0033, -0.0014, -0.0123, -0.0055, -0.0125, -0.0056, -0.0063]),
 tensor(0.))

In [6]:
def init_constant(module):
    if type(module) == nn.Linear:
        nn.init.constant_(module.weight, 1)
        nn.init.zeros_(module.bias)

net.apply(init_constant)
net[0].weight.data[0], net[0].bias.data[0], net[2].weight.data[0], net[2].bias.data[0]

(tensor([1., 1., 1., 1.]),
 tensor(0.),
 tensor([1., 1., 1., 1., 1., 1., 1., 1.]),
 tensor(0.))

In [7]:
def init_xavier(module):
    if type(module) == nn.Linear:
        nn.init.xavier_uniform_(module.weight)

def init_42(module):
    if type(module) == nn.Linear:
        nn.init.constant_(module.weight, 42)

net[0].apply(init_xavier)
net[2].apply(init_42)
print(net[0].weight.data[0])
print(net[2].weight.data)

tensor([ 0.5697, -0.4774,  0.6934,  0.4753])
tensor([[42., 42., 42., 42., 42., 42., 42., 42.]])


### Custom Initialization

In [9]:
def my_init(module):
    if type(module) == nn.Linear:
        print("Init", *[(name, param.shape) for name, param 
                        in module.named_parameters()])
        nn.init.uniform_(module.weight, -10, 10)
        module.weight.data *= module.weight.data.abs() >= 5

net.apply(my_init)
net[0].weight[:2]

Init ('weight', torch.Size([8, 4])) ('bias', torch.Size([8]))
Init ('weight', torch.Size([1, 8])) ('bias', torch.Size([1]))


tensor([[ 0.0000, -9.6393, -8.4622, -6.7703],
        [ 6.4541, -6.6499, -0.0000,  0.0000]], grad_fn=<SliceBackward0>)

In [11]:
w = torch.empty(3, 5)
nn.init.uniform_(w, -10, 10)

tensor([[-0.5547, -3.4528,  0.2173,  3.0527,  4.9985],
        [ 8.6370, -3.3186,  6.2943, -9.3402,  1.2379],
        [ 9.0176,  1.3121,  3.8541,  0.2278,  7.0012]])

In [12]:
net[0].weight.data[:] += 1
net[0].weight.data[0, 0] = 42
net[0].weight.data[0]

tensor([42.0000, -8.6393, -7.4622, -5.7703])