## File I/O

In [1]:
import torch
from torch import nn
from torch.nn import functional as F

### Loading and Saving Tensors

In [2]:
x = torch.arange(4)
torch.save(x, 'x-file')
x

tensor([0, 1, 2, 3])

In [5]:
x2 = torch.load('x-file')
x2, id(x2) == id(x)

(tensor([0, 1, 2, 3]), False)

In [6]:
x3 = torch.load('x-file')
id(x2) == id(x3)

False

In [7]:
y = torch.zeros(4)
torch.save([x, y],'x-files')
x2, y2 = torch.load('x-files')
(x2, y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [8]:
torch.save((x, y),'x-files_tup')

In [9]:
x3, y3 = torch.load('x-files_tup')
x3, y3

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [10]:
mydict = {'x': x, 'y': y}
torch.save(mydict, 'mydict')
mydict2 = torch.load('mydict')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

### Loading and Saving Model Parameters

In [11]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.LazyLinear(256)
        self.output = nn.LazyLinear(10)

    def forward(self, x):
        return self.output(F.relu(self.hidden(x)))

net = MLP()
X = torch.randn(size=(2, 20))
Y = net(X)

C:\Users\hub30\anaconda3\envs\d2l\lib\site-packages\torch\nn\modules\lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


In [12]:
torch.save(net.state_dict(), 'mlp.params')

In [15]:
net.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [14]:
clone = MLP()
clone.load_state_dict(torch.load('mlp.params'))
clone.eval()

C:\Users\hub30\anaconda3\envs\d2l\lib\site-packages\torch\nn\modules\lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


MLP(
  (hidden): LazyLinear(in_features=0, out_features=256, bias=True)
  (output): LazyLinear(in_features=0, out_features=10, bias=True)
)

In [16]:
Y_clone = clone(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])

## Exercises

### Ex. 1

#### it allows us to save the "current state of our model" - parameters, everything that's trained, thus allows us to to work with previously trained model, without needing to train it again - like creaing and saving checkpoints