# Padding and Stride

In [2]:
import torch
from torch import nn

## Padding

In [3]:
def comp_conv2d(conv2d, X):
    X = X.reshape((1, 1) + X.shape)
    Y = conv2d(X)
    return Y.reshape(Y.shape[2:])

conv2d = nn.LazyConv2d(1, kernel_size=3, padding=1)
X = torch.rand(size=(8, 8))
comp_conv2d(conv2d, X).shape

C:\Users\hub30\anaconda3\envs\d2l\lib\site-packages\torch\nn\modules\lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


torch.Size([8, 8])

In [4]:
conv2d = nn.LazyConv2d(1, kernel_size=(5, 3), padding=(2, 1))
comp_conv2d(conv2d, X).shape

C:\Users\hub30\anaconda3\envs\d2l\lib\site-packages\torch\nn\modules\lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


torch.Size([8, 8])

In [5]:
comp_conv2d(conv2d, X)

tensor([[ 0.0447, -0.1506, -0.0983, -0.0308, -0.1584, -0.1210,  0.0184, -0.1399],
        [ 0.0099, -0.1090, -0.0437, -0.1806, -0.1946, -0.0995, -0.2157, -0.4257],
        [ 0.0586, -0.1697, -0.1409, -0.2146, -0.3827, -0.0584, -0.1642, -0.4515],
        [-0.0768, -0.0198, -0.1012, -0.3971,  0.0147, -0.2650, -0.2361, -0.2850],
        [ 0.0397,  0.0117, -0.0802, -0.3390, -0.2619, -0.1750, -0.2922, -0.5487],
        [ 0.0893, -0.0071, -0.2958, -0.2759, -0.0482, -0.1135, -0.3227, -0.2585],
        [ 0.1386, -0.0679, -0.0481,  0.0318, -0.0367,  0.0356, -0.1957, -0.0734],
        [ 0.1155,  0.1883, -0.1387,  0.1896,  0.0300, -0.0208,  0.1039, -0.0363]],
       grad_fn=<ReshapeAliasBackward0>)

## Stride

In [7]:
X

tensor([[0.4995, 0.6244, 0.2311, 0.2952, 0.7274, 0.4647, 0.6886, 0.9455],
        [0.6234, 0.2300, 0.1785, 0.8924, 0.2529, 0.8179, 0.5679, 0.0797],
        [0.5646, 0.4614, 0.0660, 0.5870, 0.3192, 0.0152, 0.3291, 0.9301],
        [0.0683, 0.2824, 0.5642, 0.6457, 0.5064, 0.2265, 0.9948, 0.7419],
        [0.2043, 0.7378, 0.9056, 0.5650, 0.5751, 0.3338, 0.8511, 0.5380],
        [0.2310, 0.2161, 0.7642, 0.2398, 0.6228, 0.9721, 0.7754, 0.8645],
        [0.1836, 0.5120, 0.4659, 0.7323, 0.4303, 0.7892, 0.4831, 0.7289],
        [0.0092, 0.5919, 0.6053, 0.0815, 0.5492, 0.3885, 0.2684, 0.4582]])

In [6]:
conv2d = nn.LazyConv2d(1, kernel_size=3, padding=1, stride=2)
comp_conv2d(conv2d, X), '', comp_conv2d(conv2d, X).shape

C:\Users\hub30\anaconda3\envs\d2l\lib\site-packages\torch\nn\modules\lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


(tensor([[-0.1580, -0.2432, -0.0280, -0.1623],
         [-0.1245, -0.3426, -0.2251, -0.3645],
         [-0.2225, -0.4118, -0.3816, -0.0564],
         [-0.1769, -0.1611, -0.5319, -0.6334]], grad_fn=<ReshapeAliasBackward0>),
 '',
 torch.Size([4, 4]))

In [9]:
conv2d = nn.LazyConv2d(1, kernel_size=(3, 5), padding=(0, 1), stride=(3, 4))
comp_conv2d(conv2d, X), '', comp_conv2d(conv2d, X).shape

C:\Users\hub30\anaconda3\envs\d2l\lib\site-packages\torch\nn\modules\lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


(tensor([[-0.0215, -0.0961],
         [-0.2316, -0.1281]], grad_fn=<ReshapeAliasBackward0>),
 '',
 torch.Size([2, 2]))

## Exercises

### Ex. 1

In [16]:
def calc_dims(n_dims, k_dims, p_dims=(0, 0), s_dims=(1, 1)):
    dim1 = (n_dims[0]-k_dims[0]+p_dims[0]+s_dims[0])//s_dims[0]
    dim2 = (n_dims[1]-k_dims[1]+p_dims[1]+s_dims[1])//s_dims[1]
    return f"Output size: {dim1} x {dim2}"

In [18]:
print(comp_conv2d(conv2d, X).shape)
calc_dims((8, 8), (3, 5), (0, 1), (3, 4))

torch.Size([2, 2])


'Output size: 2 x 2'

### Ex.3

In [22]:
conv2d_ex3 = nn.LazyConv2d(1, kernel_size=(3, 5), padding_mode='replicate')
comp_conv2d(conv2d_ex3, X), '', comp_conv2d(conv2d_ex3, X).shape

(tensor([[0.2785, 0.1233, 0.8109, 0.3510],
         [0.2603, 0.5170, 0.4257, 0.1630],
         [0.2990, 0.5715, 0.3822, 0.3550],
         [0.5938, 0.5075, 0.1862, 0.4670],
         [0.2668, 0.3659, 0.2981, 0.4364],
         [0.7074, 0.2991, 0.5631, 0.5257]], grad_fn=<ReshapeAliasBackward0>),
 '',
 torch.Size([6, 4]))