# Pooling

In [1]:
import torch
from torch import nn
from d2l import torch as d2l

## Maximum Pooling and Average Pooling

In [52]:
def pool2d(X, pool_size, mode='max'):
    p_h, p_w = pool_size
    Y = torch.zeros((X.shape[0] - p_h + 1, X.shape[1] - p_w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode == 'max':
                Y[i, j] = X[i: i + p_h, j: j + p_w].max()
            elif mode == 'avg':
                Y[i, j] = X[i: i + p_h, j: j + p_w].mean()
    return Y

In [22]:
X = torch.tensor([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
X

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

In [10]:
pool2d(X, (2, 2))

tensor([[4., 5.],
        [7., 8.]])

In [11]:
pool2d(X, (2, 2), 'avg')

tensor([[2., 3.],
        [5., 6.]])

## Padding and Stride

In [35]:
X = torch.arange(16, dtype=torch.float32).reshape((1, 1, 4, 4))
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [14]:
pool2d = nn.MaxPool2d(3)
# Pooling has no model parameters, hence it needs no initialization
pool2d(X), pool2d(X).size() 

(tensor([[[[10.]]]]), torch.Size([1, 1, 1, 1]))

In [15]:
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [16]:
pool2d = nn.MaxPool2d((2, 3), stride=(2, 3), padding=(0, 1))
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [20]:
pool2d = nn.MaxPool2d((2, 3), stride=(2, 3), padding=(1, 1))
pool2d(X)

tensor([[[[ 1.,  3.],
          [ 9., 11.],
          [13., 15.]]]])

### Multiple Channels

In [36]:
torch.cat((X, X + 1), 0), torch.cat((X, X + 1), 0).size()

(tensor([[[[ 0.,  1.,  2.,  3.],
           [ 4.,  5.,  6.,  7.],
           [ 8.,  9., 10., 11.],
           [12., 13., 14., 15.]]],
 
 
         [[[ 1.,  2.,  3.,  4.],
           [ 5.,  6.,  7.,  8.],
           [ 9., 10., 11., 12.],
           [13., 14., 15., 16.]]]]),
 torch.Size([2, 1, 4, 4]))

In [37]:
X = torch.cat((X, X + 1), 1)
X, X.size()

(tensor([[[[ 0.,  1.,  2.,  3.],
           [ 4.,  5.,  6.,  7.],
           [ 8.,  9., 10., 11.],
           [12., 13., 14., 15.]],
 
          [[ 1.,  2.,  3.,  4.],
           [ 5.,  6.,  7.,  8.],
           [ 9., 10., 11., 12.],
           [13., 14., 15., 16.]]]]),
 torch.Size([1, 2, 4, 4]))

In [41]:
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X), pool2d(X).size()

(tensor([[[[ 5.,  7.],
           [13., 15.]],
 
          [[ 6.,  8.],
           [14., 16.]]]]),
 torch.Size([1, 2, 2, 2]))

# Exercises

### Ex.1

In [42]:
def corr2d(X, K):
    h, w = K.shape
    Y = torch.zeros((X.shape[0] - h + 1, X.shape[1] - w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            Y[i, j] = (X[i:i + h, j:j + w] * K).sum()
    return Y

In [48]:
X = torch.arange(16, dtype=torch.float32).reshape((4, 4))
K = torch.tensor([[1/4, 1/4], [1/4, 1/4]])
X, K

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.]]),
 tensor([[0.2500, 0.2500],
         [0.2500, 0.2500]]))

In [49]:
corr2d(X, K)

tensor([[ 2.5000,  3.5000,  4.5000],
        [ 6.5000,  7.5000,  8.5000],
        [10.5000, 11.5000, 12.5000]])

In [54]:
pool2d(X, (2, 2), 'avg')

tensor([[ 2.5000,  3.5000,  4.5000],
        [ 6.5000,  7.5000,  8.5000],
        [10.5000, 11.5000, 12.5000]])

### Ex.3.2

In [60]:
X = torch.randn(16).reshape(4, 4)
X

tensor([[ 0.2666,  1.1597,  0.3357,  0.1941],
        [ 0.7384, -1.6495,  0.0647, -0.5578],
        [-1.4027,  1.6414,  0.1335,  2.2066],
        [ 0.9052,  0.6439,  1.0339, -1.6138]])

In [64]:
X[0,0]

tensor(0.2666)

In [61]:
def max_relu(a, b):
    return a + torch.relu(b-a)

In [69]:
def maxPoolRelu(X):
    p_h = p_w = 2 
    Y = torch.zeros((X.shape[0] - p_h + 1, X.shape[1] - p_w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            m1 = max_relu(X[i, j], X[i, j + 1])
            m2 = max_relu(X[i + 1, j], X[i + 1, j + 1])
            Y[i, j] = max_relu(m1, m2)
    return Y

In [70]:
maxPoolRelu(X)

tensor([[1.1597, 1.1597, 0.3357],
        [1.6414, 1.6414, 2.2066],
        [1.6414, 1.6414, 2.2066]])

In [71]:
pool2d(X, (2, 2))

tensor([[1.1597, 1.1597, 0.3357],
        [1.6414, 1.6414, 2.2066],
        [1.6414, 1.6414, 2.2066]])

### Ex.7

Computational Complexity