In [1]:
import torch
from d2l import torch as d2l

In [5]:
X, W_xh = torch.randn(3, 1), torch.randn(1, 4)
H, W_hh = torch.randn(3, 4), torch.randn(4, 4)
(torch.matmul(X, W_xh) + torch.matmul(H, W_hh)).shape, torch.matmul(X, W_xh) + torch.matmul(H, W_hh)

(torch.Size([3, 4]),
 tensor([[ 0.8262, -0.5529, -0.4603,  0.6169],
         [ 0.5367,  0.7160,  0.9526, -2.8727],
         [ 0.8214, -2.2924,  2.3839,  2.2894]]))

In [11]:
X, W_xh, "", torch.matmul(X, W_xh).shape, torch.matmul(X, W_xh)

(tensor([[-0.2073],
         [-0.3240],
         [ 1.4183]]),
 tensor([[ 0.8811, -0.9211,  0.1809,  1.4549]]),
 '',
 torch.Size([3, 4]),
 tensor([[-0.1826,  0.1909, -0.0375, -0.3016],
         [-0.2855,  0.2984, -0.0586, -0.4714],
         [ 1.2496, -1.3063,  0.2566,  2.0635]]))

In [12]:
H, W_hh, "", torch.matmul(H, W_hh).shape, torch.matmul(H, W_hh)

(tensor([[-0.2259, -1.4386,  0.9015, -0.4955],
         [ 0.6279, -1.9178,  2.2975,  0.1484],
         [-0.1780,  0.1070,  0.6003, -1.9716]]),
 tensor([[-1.5372,  0.7984,  0.2943, -1.6339],
         [-0.3307,  0.3563,  1.4311, -1.1809],
         [ 0.4708,  0.2276,  1.5894, -1.5519],
         [ 0.4813,  0.5167, -0.5439, -0.5037]]),
 '',
 torch.Size([3, 4]),
 tensor([[ 1.0089, -0.7438, -0.4228,  0.9185],
         [ 0.8221,  0.4176,  1.0112, -2.4012],
         [-0.4282, -0.9861,  2.1273,  0.2259]]))

### Prove it mathematically

In [18]:
X, H, "", torch.cat((X, H), 1)

(tensor([[-0.2073],
         [-0.3240],
         [ 1.4183]]),
 tensor([[-0.2259, -1.4386,  0.9015, -0.4955],
         [ 0.6279, -1.9178,  2.2975,  0.1484],
         [-0.1780,  0.1070,  0.6003, -1.9716]]),
 '',
 tensor([[-0.2073, -0.2259, -1.4386,  0.9015, -0.4955],
         [-0.3240,  0.6279, -1.9178,  2.2975,  0.1484],
         [ 1.4183, -0.1780,  0.1070,  0.6003, -1.9716]]))

In [3]:
torch.matmul(torch.cat((X, H), 1), torch.cat((W_xh, W_hh), 0))

tensor([[ 3.5551,  0.0368,  2.5644, -0.2206],
        [-2.6544,  0.7300,  2.3623,  2.1469],
        [ 0.5666,  0.2159,  2.6803,  0.4508]])