In [1]:
import torch
from d2l import torch as d2l

### 1. Manual

In [17]:
X, W_xh = torch.randn(3, 1), torch.randn(1, 4)
H, W_hh = torch.randn(3, 4), torch.randn(4, 4)
out_1 = torch.matmul(X, W_xh) + torch.matmul(H, W_hh)
X.shape, X, ' ', W_xh.shape, W_xh, ' ', torch.matmul(X, W_xh).shape, torch.matmul(X, W_xh)

(torch.Size([3, 1]),
 tensor([[-0.3756],
         [ 0.7567],
         [ 0.2942]]),
 ' ',
 torch.Size([1, 4]),
 tensor([[ 0.5700, -0.7608,  0.2379,  1.1140]]),
 ' ',
 torch.Size([3, 4]),
 tensor([[-0.2141,  0.2858, -0.0893, -0.4184],
         [ 0.4313, -0.5757,  0.1800,  0.8430],
         [ 0.1677, -0.2238,  0.0700,  0.3277]]))

In [18]:
H.shape, H, ' ', W_hh.shape, W_hh, ' ', torch.matmul(H, W_hh).shape, torch.matmul(H, W_hh)

(torch.Size([3, 4]),
 tensor([[ 0.0997, -0.8356,  0.5712,  0.0232],
         [-0.5015, -0.5002, -0.6510,  0.8433],
         [-1.9418,  0.7787, -0.8462,  1.3809]]),
 ' ',
 torch.Size([4, 4]),
 tensor([[ 0.2525,  1.1246, -0.8349,  0.2517],
         [-2.2227,  0.9424,  1.6127, -0.4386],
         [-1.2032, -1.2059, -0.7457,  0.2754],
         [-0.8210,  0.8521,  0.6863,  0.3244]]),
 ' ',
 torch.Size([3, 4]),
 tensor([[ 1.1761, -1.3444, -1.8408,  0.5564],
         [ 1.0763,  0.4682,  0.6761,  0.1875],
         [-2.3364,  0.7473,  4.4557, -0.6153]]))

In [20]:
torch.matmul(X, W_xh), torch.matmul(H, W_hh), ' ', out_1

(tensor([[-0.2141,  0.2858, -0.0893, -0.4184],
         [ 0.4313, -0.5757,  0.1800,  0.8430],
         [ 0.1677, -0.2238,  0.0700,  0.3277]]),
 tensor([[ 1.1761, -1.3444, -1.8408,  0.5564],
         [ 1.0763,  0.4682,  0.6761,  0.1875],
         [-2.3364,  0.7473,  4.4557, -0.6153]]),
 ' ',
 tensor([[ 0.9620, -1.0587, -1.9301,  0.1379],
         [ 1.5076, -0.1075,  0.8561,  1.0305],
         [-2.1687,  0.5235,  4.5256, -0.2876]]))

### 2. Concatenated

In [25]:
W_xh, W_hh

(tensor([[ 0.5700, -0.7608,  0.2379,  1.1140]]),
 tensor([[ 0.2525,  1.1246, -0.8349,  0.2517],
         [-2.2227,  0.9424,  1.6127, -0.4386],
         [-1.2032, -1.2059, -0.7457,  0.2754],
         [-0.8210,  0.8521,  0.6863,  0.3244]]))

In [26]:
X, H

(tensor([[-0.3756],
         [ 0.7567],
         [ 0.2942]]),
 tensor([[ 0.0997, -0.8356,  0.5712,  0.0232],
         [-0.5015, -0.5002, -0.6510,  0.8433],
         [-1.9418,  0.7787, -0.8462,  1.3809]]))

In [24]:
cat_1 = torch.cat((X, H), 1)
cat_2 = torch.cat((W_xh, W_hh), 0)

cat_1.shape, cat_1, ' ', cat_2.shape, cat_2

(torch.Size([3, 5]),
 tensor([[-0.3756,  0.0997, -0.8356,  0.5712,  0.0232],
         [ 0.7567, -0.5015, -0.5002, -0.6510,  0.8433],
         [ 0.2942, -1.9418,  0.7787, -0.8462,  1.3809]]),
 ' ',
 torch.Size([5, 4]),
 tensor([[ 0.5700, -0.7608,  0.2379,  1.1140],
         [ 0.2525,  1.1246, -0.8349,  0.2517],
         [-2.2227,  0.9424,  1.6127, -0.4386],
         [-1.2032, -1.2059, -0.7457,  0.2754],
         [-0.8210,  0.8521,  0.6863,  0.3244]]))

In [22]:
torch.matmul(torch.cat((X, H), 1), torch.cat((W_xh, W_hh), 0))

tensor([[ 0.9620, -1.0587, -1.9301,  0.1379],
        [ 1.5076, -0.1075,  0.8561,  1.0305],
        [-2.1687,  0.5235,  4.5256, -0.2876]])